import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ExistingCalyxAdapter, type ConservatoryApi } from "./api";
import type { AuthCredentials, ConservatoryContext } from "./domain";
import { ApplicationShell } from "./components";
import { AddPlant, Dashboard, DeferredPage, NotFound, PlantDetail, PlantsPage, QRScanner, SearchPage } from "./pages";
import { parseRoute } from "./routing";

interface Session { credentials: AuthCredentials; context: ConservatoryContext }

function Login({ onAuthenticated }: { onAuthenticated(session: Session, api: ConservatoryApi): void }) {
  const [authKind, setAuthKind] = useState<"api-key"|"bearer">("api-key"); const [secret, setSecret] = useState("");
  const [eventId, setEventId] = useState(""); const [exhibitorId, setExhibitorId] = useState(""); const [categoryId, setCategoryId] = useState(""); const [error, setError] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); if (![secret,eventId,exhibitorId,categoryId].every((x) => x.trim())) { setError("Authentication and collection context are required."); return; } setLoading(true); setError(null); const session: Session = { credentials: { kind: authKind, value: secret.trim() }, context: { eventId: eventId.trim(), exhibitorId: exhibitorId.trim(), categoryId: categoryId.trim() } }; const api = new ExistingCalyxAdapter(import.meta.env.VITE_CALYX_API_BASE || "", session.credentials, session.context); try { await api.authenticate(); sessionStorage.setItem("calyx-conservatory-session", JSON.stringify(session)); onAuthenticated(session, api); } catch (reason) { setError(reason instanceof Error ? reason.message : "Authentication failed."); } finally { setLoading(false); } }
  return <main className="login"><section><span className="eyebrow">Orchid Continuum</span><h1>Enter My Conservatory</h1><p>Authenticate to view private collection records. Credentials remain in this browser session and are never written to local storage.</p><form onSubmit={submit}>{error && <p className="form-error" role="alert">{error}</p>}<label>Authentication method<select value={authKind} onChange={(e) => setAuthKind(e.target.value as never)}><option value="api-key">Calyx API key</option><option value="bearer">Owner session token</option></select></label><label>{authKind === "api-key" ? "API key" : "Session token"}<input type="password" autoComplete="current-password" value={secret} onChange={(e) => setSecret(e.target.value)} required/></label><fieldset><legend>Existing backend collection context</legend><label>Judging event ID<input value={eventId} onChange={(e) => setEventId(e.target.value)} required/></label><label>Exhibitor ID<input value={exhibitorId} onChange={(e) => setExhibitorId(e.target.value)} required/></label><label>Category ID<input value={categoryId} onChange={(e) => setCategoryId(e.target.value)} required/></label></fieldset><button disabled={loading}>{loading ? "Authenticating…" : "Open conservatory"}</button></form><small>My Conservatory uses existing Calyx endpoints through a documented adapter. Missing product APIs are not simulated.</small></section></main>;
}

export default function App() {
  const [route, setRoute] = useState(() => parseRoute(window.location.pathname)); const [session, setSession] = useState<Session | null>(() => { try { return JSON.parse(sessionStorage.getItem("calyx-conservatory-session") || "null") as Session | null; } catch { return null; } }); const [api, setApi] = useState<ConservatoryApi | null>(() => session ? new ExistingCalyxAdapter(import.meta.env.VITE_CALYX_API_BASE || "", session.credentials, session.context) : null); const [notification, setNotification] = useState<string | null>(null);
  useEffect(() => { const listener = () => { setRoute(parseRoute(window.location.pathname)); requestAnimationFrame(() => document.getElementById("main-content")?.focus()); }; window.addEventListener("popstate", listener); return () => window.removeEventListener("popstate", listener); }, []);
  useEffect(() => { if (!notification) return; const timeout = window.setTimeout(() => setNotification(null), 5000); return () => clearTimeout(timeout); }, [notification]);
  const page = useMemo(() => { if (!api) return null; switch (route.page) { case "dashboard": return <Dashboard api={api}/>; case "plants": return <PlantsPage api={api}/>; case "plant": return <PlantDetail api={api} plantId={route.plantId}/>; case "add": return <AddPlant api={api} notify={setNotification}/>; case "search": return <SearchPage api={api}/>; case "scan": return <QRScanner api={api}/>; case "deferred": return <DeferredPage feature={route.feature}/>; default: return <NotFound/>; } }, [api, route]);
  if (!session || !api) return <Login onAuthenticated={(next, nextApi) => { setSession(next); setApi(nextApi); }}/>;
  return <ApplicationShell onSignOut={() => { sessionStorage.removeItem("calyx-conservatory-session"); setSession(null); setApi(null); }}><div className="page-container">{page}</div>{notification && <div className="toast" role="status">{notification}</div>}</ApplicationShell>;
}
