import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import type { ConservatoryApi } from "./api";
import { filterAndPage } from "./domain";
import { useAsync } from "./hooks";
import { navigate } from "./routing";
import { CitationPanel, CollectionTable, EmptyState, ErrorState, FilterPanel, Link, LoadingState, OrchidCard, PageHeader, Pagination, PlantHeader, ProvenanceViewer, QRDisplay, SearchField, SearchResultCard } from "./components";

export function Dashboard({ api }: { api: ConservatoryApi }) {
  const state = useAsync(() => api.listPlants(), [api]);
  if (state.loading) return <LoadingState label="Preparing your conservatory"/>;
  if (state.error) return <ErrorState error={state.error} retry={state.retry}/>;
  const plants = state.value || [];
  const recent = [...plants].sort((a, b) => Date.parse(b.collectionMetadata.createdAt) - Date.parse(a.collectionMetadata.createdAt)).slice(0, 3);
  return <><PageHeader eyebrow="Overview" title="Your orchids, in context" description="A private view of the living collection records currently available from Calyx." actions={<Link href="/conservatory/plants/new" className="button">Add a plant</Link>}/>
    <section className="metrics" aria-label="Collection summary"><article><span>Collection</span><strong>{plants.length}</strong><small>backend plant records</small></article><article><span>QR linked</span><strong>{plants.filter((p) => p.qrIdentifier).length}</strong><small>scannable identifiers</small></article><article><span>Needs identification</span><strong>{plants.filter((p) => p.uncertainIdentification).length}</strong><small>uncertain or missing names</small></article><article><span>Reminders</span><strong>—</strong><small>planned for a future BUILD</small></article></section>
    <section className="section-heading"><div><span className="eyebrow">Recent activity</span><h2>Recently added</h2></div><Link href="/conservatory/plants">View all plants</Link></section>
    {recent.length ? <div className="card-grid">{recent.map((plant) => <OrchidCard plant={plant} key={plant.id}/>)}</div> : <EmptyState title="Your collection is ready" message="No plants are available for this event yet." action={<Link className="button" href="/conservatory/plants/new">Add the first plant</Link>}/>}
    <section className="quick-actions" aria-labelledby="quick-actions"><h2 id="quick-actions">Quick actions</h2><div><Link href="/conservatory/plants">Browse collection</Link><Link href="/conservatory/search">Search records</Link><Link href="/conservatory/scan">Scan a QR code</Link></div></section></>;
}

export function PlantsPage({ api }: { api: ConservatoryApi }) {
  const state = useAsync(() => api.listPlants(), [api]);
  const [query, setQuery] = useState(""); const [category, setCategory] = useState("");
  const [sort, setSort] = useState<"name-asc"|"name-desc"|"newest"|"oldest">("name-asc"); const [page, setPage] = useState(1);
  const result = useMemo(() => filterAndPage(state.value || [], { query, categoryId: category || undefined, sort, page, pageSize: 10 }), [state.value, query, category, sort, page]);
  useEffect(() => setPage(1), [query, category, sort]);
  if (state.loading) return <LoadingState/>; if (state.error) return <ErrorState error={state.error} retry={state.retry}/>;
  return <><PageHeader eyebrow="Collection" title="My Plants" description="Sort and filter authenticated plant records without changing scientific or provenance fields." actions={<Link href="/conservatory/plants/new" className="button">Add plant</Link>}/><SearchField value={query} onChange={setQuery}/><FilterPanel sort={sort} category={category} onSort={setSort} onCategory={setCategory}/>{result.total ? <><CollectionTable plants={result.items}/><Pagination {...result} onPage={setPage}/></> : <EmptyState title="No plants match" message={query || category ? "Clear or revise the current filters." : "The backend returned an empty collection."}/>}</>;
}

export function PlantDetail({ api, plantId }: { api: ConservatoryApi; plantId: string }) {
  const state = useAsync(() => api.getPlant(plantId), [api, plantId]);
  if (state.loading) return <LoadingState label="Loading plant record"/>; if (state.error) return <ErrorState error={state.error} retry={state.retry}/>; if (!state.value) return null;
  const plant = state.value;
  return <><div className="breadcrumbs"><Link href="/conservatory">Overview</Link><span>/</span><Link href="/conservatory/plants">My Plants</Link><span>/</span><span aria-current="page">{plant.displayName}</span></div><PlantHeader plant={plant}/><div className="detail-grid"><section className="panel"><h2>Scientific identity</h2><dl><dt>Accepted name</dt><dd>{plant.acceptedScientificName || "Not supplied by current backend"}</dd><dt>Synonym status</dt><dd>{plant.synonymStatus === "not-supplied" ? "Not supplied" : plant.synonymStatus}</dd><dt>Hybrid notation</dt><dd>{plant.hybridNotation || "Not recorded"}</dd><dt>Authorship</dt><dd>{plant.authorship || "Not recorded"}</dd><dt>Parentage</dt><dd>{plant.parentage || "Not recorded"}</dd></dl></section><section className="panel"><h2>Collection record</h2><dl><dt>Location</dt><dd>{plant.location || "Restricted or not recorded"}</dd><dt>Notes</dt><dd>{plant.notes || "No notes"}</dd><dt>Created</dt><dd>{new Date(plant.collectionMetadata.createdAt).toLocaleString()}</dd><dt>Category</dt><dd>{plant.collectionMetadata.categoryId}</dd></dl><QRDisplay value={plant.qrIdentifier}/></section></div><section className="panel"><h2>Photographs</h2>{plant.photographs.length ? <div className="photo-grid">{plant.photographs.map((src) => <img src={src} alt={`Documented view of ${plant.displayName}`} key={src}/>)}</div> : <p>No licensed photographs are available from the current backend.</p>}</section><ProvenanceViewer records={plant.provenance}/><CitationPanel citations={plant.citations}/></>;
}

export function AddPlant({ api, notify }: { api: ConservatoryApi; notify(message: string): void }) {
  const [name, setName] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); const trimmed = name.trim(); if (trimmed.length < 2) { setError("Enter a plant name with at least two characters."); return; } setSaving(true); setError(null); try { const plant = await api.addPlant({ name: trimmed, notes }); notify(`${plant.displayName} was added to the collection.`); navigate(`/conservatory/plants/${plant.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The plant could not be saved."); } finally { setSaving(false); } }
  return <><PageHeader eyebrow="Collection" title="Add Plant" description="Create a real backend plant record using your configured event, exhibitor, and category context."/><form className="editor" onSubmit={submit} noValidate>{error && <div className="form-error" role="alert"><strong>Check this plant</strong><span>{error}</span></div>}<label>Scientific or collection name<span>Required</span><input autoFocus required minLength={2} value={name} onChange={(e) => setName(e.target.value)} aria-describedby="name-help"/></label><small id="name-help">Use the name exactly as documented. Uncertainty markers such as “cf.” are preserved.</small><label>Collection notes<textarea rows={5} value={notes} onChange={(e) => setNotes(e.target.value)}/></label><div className="form-actions"><Link href="/conservatory/plants">Cancel</Link><button disabled={saving}>{saving ? "Saving…" : "Save plant"}</button></div></form></>;
}

export function SearchPage({ api }: { api: ConservatoryApi }) {
  const state = useAsync(() => api.listPlants(), [api]); const [query, setQuery] = useState(""); const [submitted, setSubmitted] = useState(""); const [sort, setSort] = useState<"name-asc"|"name-desc"|"newest"|"oldest">("name-asc"); const [category, setCategory] = useState(""); const [page, setPage] = useState(1);
  const result = useMemo(() => filterAndPage(state.value || [], { query: submitted, categoryId: category || undefined, sort, page, pageSize: 9 }), [state.value, submitted, category, sort, page]);
  if (state.loading) return <LoadingState label="Preparing search"/>; if (state.error) return <ErrorState error={state.error} retry={state.retry}/>;
  return <><PageHeader eyebrow="Discovery" title="Search your collection" description="Search the real event collection by documented name or notes. Synonym coverage depends on backend data."/><SearchField value={query} onChange={setQuery} onSubmit={() => { setSubmitted(query); setPage(1); }}/><FilterPanel sort={sort} category={category} onSort={setSort} onCategory={setCategory}/><p role="status" className="result-count">{result.total} result{result.total === 1 ? "" : "s"}</p>{result.total ? <><div className="card-grid">{result.items.map((plant) => <SearchResultCard plant={plant} key={plant.id}/>)}</div><Pagination {...result} onPage={setPage}/></> : <EmptyState title="No matching records" message="Try a different scientific name, uncertainty marker, or note."/>}</>;
}

export function QRScanner({ api }: { api: ConservatoryApi }) {
  const [value, setValue] = useState(""); const [error, setError] = useState<string | null>(null); const [scanning, setScanning] = useState(false); const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null);
  useEffect(() => () => stream.current?.getTracks().forEach((track) => track.stop()), []);
  async function resolve(raw = value) { setError(null); try { const plant = await api.resolveQr(raw); navigate(`/conservatory/plants/${plant.id}`); } catch (reason) { setError(reason instanceof Error ? reason.message : "QR identifier could not be resolved."); } }
  async function scan() { setError(null); if (!("BarcodeDetector" in window)) { setError("Camera QR decoding is not available in this browser. Enter the identifier below."); return; } try { const media = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } }); stream.current = media; if (video.current) { video.current.srcObject = media; await video.current.play(); } setScanning(true); const Detector = (window as unknown as { BarcodeDetector: new (options: {formats: string[]} ) => { detect(source: HTMLVideoElement): Promise<Array<{rawValue: string}>> } }).BarcodeDetector; const detector = new Detector({ formats: ["qr_code"] }); const poll = async () => { if (!video.current || !stream.current) return; const codes = await detector.detect(video.current); if (codes[0]?.rawValue) { stream.current.getTracks().forEach((track) => track.stop()); stream.current = null; setScanning(false); setValue(codes[0].rawValue); await resolve(codes[0].rawValue); return; } requestAnimationFrame(() => void poll()); }; void poll(); } catch { setError("Camera permission was denied or no camera is available. Enter the identifier below."); setScanning(false); } }
  return <><PageHeader eyebrow="Identify" title="Scan a plant" description="Decode a QR identifier and resolve it against the current authenticated Calyx backend."/><section className="scanner"><div className="camera"><video ref={video} muted playsInline aria-label="QR camera preview"/><span>{scanning ? "Point the camera at a Calyx QR code" : "Camera is off"}</span><button onClick={() => void scan()} disabled={scanning}>{scanning ? "Scanning…" : "Start camera"}</button></div><form onSubmit={(e) => { e.preventDefault(); void resolve(); }}><label>QR or plant identifier<input value={value} onChange={(e) => setValue(e.target.value)} placeholder="calyx:plant:…"/></label>{error && <p role="alert" className="inline-error">{error}</p>}<button>Resolve plant</button><small>Offline scanning is deferred. QR data contains an identifier, never mutable plant data.</small></form></section></>;
}

export function DeferredPage({ feature }: { feature: string }) { const label = feature.replace(/(^|-)\w/g, (match) => match.toUpperCase()); return <><PageHeader eyebrow="Planned capability" title={label} description="This route is reserved by the BUILD-091 navigation specification."/><EmptyState title={`${label} is planned`} message="The specification exists, but implementation is intentionally deferred to a future BUILD phase. No placeholder data is shown." action={<Link className="button" href="/conservatory">Return to overview</Link>}/></>; }
export function NotFound() { return <EmptyState title="Page not found" message="This route is not part of the approved My Conservatory navigation graph." action={<Link className="button" href="/conservatory">Return to overview</Link>}/>; }
