from collections.abc import Mapping, Sequence
from typing import Any, Protocol


class OntologyRepository(Protocol):
    def create_registry(self, data: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def update_registry(self, registry_id: int, changes: Mapping[str, Any], actor: str, reason: str) -> dict[str, Any] | None: ...
    def set_registry_status(self, registry_id: int, status: str, actor: str, reason: str) -> dict[str, Any] | None: ...
    def list_registries(self) -> list[dict[str, Any]]: ...
    def get_registry(self, registry_id: int) -> dict[str, Any] | None: ...
    def create_term(self, data: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def update_term(self, term_id: int, changes: Mapping[str, Any], actor: str, reason: str) -> dict[str, Any] | None: ...
    def get_term(self, term_id: int) -> dict[str, Any] | None: ...
    def add_synonym(self, term_id: int, data: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def search_terms(self, query: str, registry_id: int | None = None) -> list[dict[str, Any]]: ...
    def hierarchy_ancestors(self, term_id: int) -> list[int]: ...
    def get_entity_candidate(self, candidate_id: int) -> dict[str, Any] | None: ...
    def get_session_entity_candidates(self, session_id: int) -> list[dict[str, Any]]: ...
    def create_resolution(self, candidate_id: int, suggestion: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def list_resolutions(self, candidate_id: int) -> list[dict[str, Any]]: ...
    def decide_resolution(self, resolution_id: int, status: str, actor: str, reason: str) -> dict[str, Any] | None: ...
    def evidence_source(self, evidence_object_id: int) -> dict[str, Any] | None: ...
    def create_evidence_entry(self, evidence_object_id: int, data: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def get_evidence_entry(self, evidence_object_id: int) -> dict[str, Any] | None: ...
    def validate_evidence_entry(self, evidence_object_id: int, status: str, details: Mapping[str, Any], actor: str) -> dict[str, Any] | None: ...
    def readiness_context(self, candidate_id: int) -> dict[str, Any] | None: ...
    def session_candidate_ids(self, session_id: int) -> list[int]: ...
    def save_readiness(self, candidate_id: int, result: Mapping[str, Any], actor: str) -> dict[str, Any]: ...
    def get_readiness(self, candidate_id: int) -> dict[str, Any] | None: ...


class ResolutionEngine(Protocol):
    def suggestions(self, original: str, terms: Sequence[Mapping[str, Any]]) -> list[dict[str, Any]]: ...
