CREATE SCHEMA IF NOT EXISTS oc_document_intelligence;
CREATE TABLE IF NOT EXISTS oc_document_intelligence.records (
 record_id BIGSERIAL PRIMARY KEY, revision_id BIGINT NOT NULL REFERENCES oc_import.document_revisions(revision_id), registry_id BIGINT NOT NULL REFERENCES oc_sources.document_inventory(inventory_id), source_sha256 CHAR(64) NOT NULL,
 source_filename TEXT NOT NULL, source_mime_type TEXT NOT NULL, source_provenance JSONB NOT NULL, license JSONB NOT NULL DEFAULT '{}', copyright_display_status TEXT NOT NULL DEFAULT 'RESTRICTED', supersedes_record_id BIGINT REFERENCES oc_document_intelligence.records(record_id), created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(revision_id));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.classifications (
 classification_id BIGSERIAL PRIMARY KEY, record_id BIGINT NOT NULL REFERENCES oc_document_intelligence.records(record_id), document_class TEXT NOT NULL, subclass TEXT, confidence NUMERIC NOT NULL CHECK(confidence BETWEEN 0 AND 1), method TEXT NOT NULL, version TEXT NOT NULL, evidence JSONB NOT NULL, operator_override BOOLEAN NOT NULL DEFAULT FALSE, override_reason TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS oc_document_intelligence.source_assessments (
 assessment_id BIGSERIAL PRIMARY KEY, record_id BIGINT NOT NULL REFERENCES oc_document_intelligence.records(record_id), peer_reviewed TEXT NOT NULL DEFAULT 'UNKNOWN', publication JSONB NOT NULL DEFAULT '{}', ai_generated TEXT NOT NULL DEFAULT 'UNKNOWN', human_reviewed TEXT NOT NULL DEFAULT 'UNKNOWN', citations_status TEXT NOT NULL DEFAULT 'UNKNOWN', authority_category TEXT, evidence_tier TEXT, reliability JSONB NOT NULL DEFAULT '{}', temporal_status TEXT NOT NULL DEFAULT 'UNKNOWN', review_after DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS oc_document_intelligence.extraction_runs (
 extraction_run_id BIGSERIAL PRIMARY KEY, record_id BIGINT NOT NULL REFERENCES oc_document_intelligence.records(record_id), extractor_version TEXT NOT NULL, ruleset_version TEXT NOT NULL, configuration_hash CHAR(64) NOT NULL, state TEXT NOT NULL CHECK(state IN ('PENDING','CLASSIFYING','CLASSIFIED','EXTRACTING','STRUCTURED','DERIVING_OBJECTS','READY_FOR_REVIEW','COMPLETED','PARTIAL','FAILED','CANCELLED')), normalized_text TEXT, layout JSONB NOT NULL DEFAULT '{}', quality JSONB NOT NULL DEFAULT '{}', last_completed_boundary TEXT, cancellation_requested_at TIMESTAMPTZ, started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), completed_at TIMESTAMPTZ, cancelled_at TIMESTAMPTZ, UNIQUE(record_id,extractor_version,ruleset_version,configuration_hash));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.structural_objects (
 structural_id BIGSERIAL PRIMARY KEY, extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id), parent_id BIGINT REFERENCES oc_document_intelligence.structural_objects(structural_id), section_type TEXT NOT NULL, source_heading TEXT, normalized_heading TEXT, hierarchy_level INTEGER, sequence INTEGER NOT NULL, page_start INTEGER,page_end INTEGER,char_start BIGINT,char_end BIGINT,complete_text TEXT NOT NULL, confidence NUMERIC, warnings JSONB NOT NULL DEFAULT '[]', source_anchor JSONB NOT NULL, UNIQUE(extraction_run_id,sequence));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.source_anchors (anchor_id BIGSERIAL PRIMARY KEY,revision_id BIGINT NOT NULL REFERENCES oc_import.document_revisions(revision_id),extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),structural_id BIGINT NOT NULL REFERENCES oc_document_intelligence.structural_objects(structural_id),page_number INTEGER,logical_unit TEXT,block_id TEXT,char_start BIGINT,char_end BIGINT,bounding_region JSONB,ordered_span INTEGER NOT NULL,extraction_method TEXT NOT NULL,ocr_derived BOOLEAN NOT NULL DEFAULT FALSE,confidence NUMERIC, UNIQUE(structural_id,ordered_span));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.protocols (
 protocol_id BIGSERIAL PRIMARY KEY, extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id), canonical_title TEXT NOT NULL, protocol_type TEXT NOT NULL, complete_text TEXT NOT NULL, attributes JSONB NOT NULL, source_anchors JSONB NOT NULL, parent_canonical_protocol_id BIGINT REFERENCES oc_document_intelligence.protocols(protocol_id), adaptation JSONB, approval_state TEXT NOT NULL DEFAULT 'CANONICAL');
CREATE TABLE IF NOT EXISTS oc_document_intelligence.protocol_source_spans (protocol_id BIGINT NOT NULL REFERENCES oc_document_intelligence.protocols(protocol_id),structural_id BIGINT NOT NULL REFERENCES oc_document_intelligence.structural_objects(structural_id),sequence INTEGER NOT NULL,source_anchor JSONB NOT NULL,PRIMARY KEY(protocol_id,sequence));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.result_packages (
 result_package_id BIGSERIAL PRIMARY KEY, extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id), title TEXT, evidence JSONB NOT NULL, source_anchors JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.result_package_components (component_id BIGSERIAL PRIMARY KEY,result_package_id BIGINT NOT NULL REFERENCES oc_document_intelligence.result_packages(result_package_id),component_type TEXT NOT NULL,content JSONB NOT NULL,source_anchor JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.media_objects (
 media_id BIGSERIAL PRIMARY KEY, extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id), object_type TEXT NOT NULL,label TEXT,title TEXT,caption TEXT,page INTEGER,source_region JSONB,links JSONB NOT NULL DEFAULT '{}',extraction_quality JSONB NOT NULL DEFAULT '{}',copyright_display_status TEXT NOT NULL DEFAULT 'RESTRICTED');
CREATE TABLE IF NOT EXISTS oc_document_intelligence.table_objects (
 table_id BIGSERIAL PRIMARY KEY, extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id), label TEXT,title TEXT,caption TEXT,complete_table JSONB NOT NULL,source_anchor JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.identification_keys (key_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),title TEXT,source_anchor JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.taxonomic_treatments (treatment_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),accepted_name TEXT,rank TEXT,treatment JSONB NOT NULL,ordered_sections JSONB NOT NULL,source_anchors JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.strategic_insights (insight_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),insight_type TEXT NOT NULL,content JSONB NOT NULL,source_anchor JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.identification_key_nodes (node_id BIGSERIAL PRIMARY KEY,key_id BIGINT NOT NULL REFERENCES oc_document_intelligence.identification_keys(key_id),parent_id BIGINT REFERENCES oc_document_intelligence.identification_key_nodes(node_id),couplet TEXT,lead TEXT NOT NULL,target_node_id BIGINT,original_wording TEXT NOT NULL,source_anchor JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.extracted_claims (claim_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),structural_id BIGINT REFERENCES oc_document_intelligence.structural_objects(structural_id),claim_text TEXT NOT NULL,claim_type TEXT NOT NULL,normalized JSONB NOT NULL,evidence_tier TEXT,verification_state TEXT NOT NULL DEFAULT 'UNVERIFIED',source_anchor JSONB NOT NULL,published BOOLEAN NOT NULL DEFAULT FALSE CHECK(published=FALSE));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.candidate_events (event_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),event_type TEXT NOT NULL,event_data JSONB NOT NULL,verification_state TEXT NOT NULL DEFAULT 'UNVERIFIED',published BOOLEAN NOT NULL DEFAULT FALSE CHECK(published=FALSE));
CREATE TABLE IF NOT EXISTS oc_document_intelligence.retrieval_chunks (chunk_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),structural_id BIGINT REFERENCES oc_document_intelligence.structural_objects(structural_id),protocol_id BIGINT REFERENCES oc_document_intelligence.protocols(protocol_id),text TEXT NOT NULL,text_kind TEXT NOT NULL,source_anchor JSONB NOT NULL,complete_object_pointer JSONB NOT NULL);
CREATE TABLE IF NOT EXISTS oc_document_intelligence.review_items (review_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),structural_id BIGINT REFERENCES oc_document_intelligence.structural_objects(structural_id),condition TEXT NOT NULL,details JSONB NOT NULL,state TEXT NOT NULL DEFAULT 'OPEN',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS oc_document_intelligence.extraction_warnings (warning_id BIGSERIAL PRIMARY KEY,extraction_run_id BIGINT NOT NULL REFERENCES oc_document_intelligence.extraction_runs(extraction_run_id),structural_id BIGINT REFERENCES oc_document_intelligence.structural_objects(structural_id),adapter TEXT,code TEXT NOT NULL,message TEXT,source_anchor JSONB,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS intelligence_revision_idx ON oc_document_intelligence.records(revision_id);
CREATE INDEX IF NOT EXISTS intelligence_review_queue_idx ON oc_document_intelligence.review_items(state,created_at);
CREATE INDEX IF NOT EXISTS intelligence_run_history_idx ON oc_document_intelligence.extraction_runs(record_id,started_at DESC);
CREATE INDEX IF NOT EXISTS intelligence_anchor_revision_idx ON oc_document_intelligence.source_anchors(revision_id,page_number,ordered_span);
CREATE OR REPLACE FUNCTION oc_document_intelligence.reject_canonical_mutation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'canonical evidence is immutable'; END $$;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_trigger WHERE tgname='intelligence_records_immutable') THEN CREATE TRIGGER intelligence_records_immutable BEFORE UPDATE OR DELETE ON oc_document_intelligence.records FOR EACH ROW EXECUTE FUNCTION oc_document_intelligence.reject_canonical_mutation(); END IF; END $$;
