from typing import Any, Protocol

from .models import CandidateRequest, PublicationPolicy


class PublicationRegistry(Protocol):
    def create_policy(
        self, policy: PublicationPolicy, actor: str
    ) -> dict[str, Any]: ...
    def activate_policy(self, policy_id: str, version: int, actor: str) -> None: ...
    def create_candidate(self, request: CandidateRequest) -> dict[str, Any]: ...
    def authorize(
        self, publication_id: int, actor: str, authority=None
    ) -> dict[str, Any]: ...
    def candidate(self, publication_id: int) -> dict[str, Any] | None: ...
    def audit_history(
        self, artifact_type: str, artifact_id: int
    ) -> list[dict[str, Any]]: ...
