import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it } from "vitest";
import { AddPlant, Dashboard, DeferredPage, PlantDetail, PlantsPage, QRScanner, SearchPage } from "../pages";
import { fakeApi } from "./fixtures";

describe("working pages",()=>{
  it("renders dashboard with real API summary and recent activity",async()=>{render(<Dashboard api={fakeApi()}/>);expect(await screen.findByRole("heading",{name:"Your orchids, in context"})).toBeVisible();expect(screen.getByText("Cattleya labiata")).toBeVisible();expect(screen.getAllByText("1",{selector:"strong"})).toHaveLength(2);});
  it("renders, searches, sorts, and links collection rows",async()=>{render(<PlantsPage api={fakeApi()}/>);expect(await screen.findByRole("table")).toBeVisible();await userEvent.type(screen.getByRole("searchbox"),"missing");expect(screen.getByRole("heading",{name:"No plants match"})).toBeVisible();});
  it("shows scientific limitations, QR, provenance, and privacy-preserving location",async()=>{render(<PlantDetail api={fakeApi()} plantId="plant-1"/>);expect(await screen.findByRole("heading",{name:/Cattleya labiata/})).toBeVisible();expect(screen.getByText("Not supplied by current backend")).toBeVisible();expect(screen.getByText("Restricted or not recorded")).toBeVisible();expect(screen.getByRole("heading",{name:"Provenance"})).toBeVisible();expect(screen.getByText("calyx:plant:plant-1")).toBeVisible();});
  it("validates and persists Add Plant through the adapter",async()=>{const api=fakeApi();render(<AddPlant api={api} notify={vi.fn()}/>);await userEvent.click(screen.getByRole("button",{name:"Save plant"}));expect(screen.getByRole("alert")).toHaveTextContent("at least two");await userEvent.type(screen.getByLabelText(/Scientific or collection name/),"Cattleya labiata");await userEvent.click(screen.getByRole("button",{name:"Save plant"}));await waitFor(()=>expect(api.addPlant).toHaveBeenCalledWith({name:"Cattleya labiata",notes:""}));});
  it("searches documented names through real collection data",async()=>{render(<SearchPage api={fakeApi()}/>);const input=await screen.findByRole("searchbox");await userEvent.type(input,"Cattleya");await userEvent.click(screen.getByRole("button",{name:"Search"}));expect(screen.getByText("1 result")).toBeVisible();});
  it("resolves manually entered QR identifiers",async()=>{const api=fakeApi();render(<QRScanner api={api}/>);await userEvent.type(screen.getByLabelText("QR or plant identifier"),"calyx:plant:plant-1");await userEvent.click(screen.getByRole("button",{name:"Resolve plant"}));await waitFor(()=>expect(api.resolveQr).toHaveBeenCalledWith("calyx:plant:plant-1"));});
  it("labels deferred routes without fabricated data",()=>{render(<DeferredPage feature="reports"/>);expect(screen.getByRole("heading",{name:"Reports is planned"})).toBeVisible();expect(screen.getByText(/No placeholder data/)).toBeVisible();});
  it("shows recoverable errors",async()=>{render(<Dashboard api={fakeApi({listPlants:vi.fn().mockRejectedValue(new Error("Backend unavailable"))})}/>);expect(await screen.findByRole("alert")).toHaveTextContent("Backend unavailable");expect(screen.getByRole("button",{name:"Try again"})).toBeVisible();});
});
