from typing import Any, Protocol, Sequence

from .models import EntityDraft, EvidenceDraft, ExtractionStage, RelationshipDraft


class SemanticCandidateRepository(Protocol):
    def create_session(self, document_id: int, actor: str, provenance: dict[str, Any]) -> dict[str, Any]: ...
    def get_session(self, session_id: int) -> dict[str, Any] | None: ...
    def transition_session(self, session_id: int, target: ExtractionStage, actor: str, error: str | None = None) -> dict[str, Any]: ...
    def load_document(self, document_id: int) -> dict[str, Any] | None: ...
    def save_candidates(self, session_id: int, entities: Sequence[EntityDraft], relationships: Sequence[RelationshipDraft], evidence: Sequence[EvidenceDraft], actor: str) -> None: ...
    def get_evidence(self, evidence_id: int) -> dict[str, Any] | None: ...
    def get_candidates(self, session_id: int) -> dict[str, Any] | None: ...
    def update_candidate(self, candidate_id: int, changes: dict[str, Any], actor: str, reason: str) -> dict[str, Any] | None: ...


class SemanticReviewRepository(Protocol):
    def record_review(self, session_id: int, candidate_ids: Sequence[int], decision: str, actor: str, notes: str | None) -> dict[str, Any]: ...


class SemanticExtractor(Protocol):
    def extract_entities(self, text: str) -> list[EntityDraft]: ...
    def extract_relationships(self, text: str, entities: Sequence[EntityDraft]) -> list[RelationshipDraft]: ...
    def build_evidence(self, text: str, sha256: str, relationships: Sequence[RelationshipDraft], document_id: int) -> list[EvidenceDraft]: ...
