from __future__ import annotations

import os
import re
from dataclasses import dataclass
from datetime import datetime, timezone

from .github import FileChange, GitHubEngineeringClient

_SLUG = re.compile(r"[^a-z0-9]+")


@dataclass(frozen=True)
class EngineeringProposal:
    title: str
    summary: str
    branch: str
    issue_body: str
    pull_request_body: str
    test_plan: tuple[str, ...]

    def to_dict(self) -> dict:
        return {
            "title": self.title,
            "summary": self.summary,
            "branch": self.branch,
            "issue_body": self.issue_body,
            "pull_request_body": self.pull_request_body,
            "test_plan": list(self.test_plan),
            "autonomous_merge": False,
            "production_deployment": False,
        }


class CalyxEngineeringService:
    def __init__(self, client: GitHubEngineeringClient | None = None) -> None:
        repository = os.getenv("CALYX_ENGINEERING_REPOSITORY", "jsp1440/orchid-calyx-backend")
        self.repository = repository
        self.client = client

    @staticmethod
    def enabled() -> bool:
        return (
            os.getenv("CALYX_ENGINEERING_ENABLED", "").lower() == "true"
            and os.getenv("CALYX_ENGINEERING_MODE", "").lower() == "preproduction"
        )

    def propose(self, *, finding_id: str, title: str, summary: str, recommendation: str) -> EngineeringProposal:
        slug = _SLUG.sub("-", title.casefold()).strip("-")[:48] or "finding"
        branch = f"calyx/{finding_id[:8]}-{slug}"
        issue_body = (
            "## Calyx finding\n"
            f"Finding: `{finding_id}`\n\n"
            f"{summary}\n\n"
            "## Recommended bounded change\n"
            f"{recommendation}\n\n"
            "## Governance\n"
            "Generated by the preproduction Calyx engineering loop. No autonomous merge or deployment is permitted."
        )
        pr_body = (
            f"Implements governed follow-up for Calyx finding `{finding_id}`.\n\n"
            "- Draft pull request only\n"
            "- CI must pass\n"
            "- Human review remains required for merge\n"
            "- No deployment or scientific publication authority"
        )
        return EngineeringProposal(
            title=title,
            summary=summary,
            branch=branch,
            issue_body=issue_body,
            pull_request_body=pr_body,
            test_plan=("compile", "ruff", "focused pytest", "existing repository CI"),
        )

    def execute(
        self,
        *,
        proposal: EngineeringProposal,
        changes: list[FileChange],
        approved: bool,
        base: str = "main",
    ) -> dict:
        if not self.enabled():
            raise RuntimeError("CALYX_ENGINEERING_DISABLED")
        if not approved:
            raise PermissionError("ENGINEERING_APPROVAL_REQUIRED")
        if not changes:
            raise ValueError("ENGINEERING_CHANGESET_REQUIRED")
        if len(changes) > 20:
            raise ValueError("ENGINEERING_CHANGESET_TOO_LARGE")
        for change in changes:
            change.validate()

        client = self.client or GitHubEngineeringClient(self.repository)
        base_sha = client.default_branch_sha(base)
        issue = client.create_issue(proposal.title, proposal.issue_body)
        client.create_branch(proposal.branch, base_sha)
        commits = [client.put_file(proposal.branch, change) for change in changes]
        pull_request = client.open_pull_request(
            proposal.title,
            proposal.pull_request_body,
            proposal.branch,
            base,
        )
        return {
            "status": "draft_pull_request_opened",
            "repository": self.repository,
            "issue_number": issue.get("number"),
            "issue_url": issue.get("html_url"),
            "branch": proposal.branch,
            "commits": len(commits),
            "pull_request_number": pull_request.get("number"),
            "pull_request_url": pull_request.get("html_url"),
            "created_at": datetime.now(timezone.utc).isoformat(),
            "autonomous_merge": False,
            "deployment_activated": False,
        }
