"""Compact, deterministic work packets for provider-efficient execution."""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass
from typing import Iterable

_FILE_RE = re.compile(
    r"(?<![\w.-])(?:[\w.-]+/)+(?:[\w.-]+\.(?:py|yml|yaml|json|md|ts|tsx|js|jsx|sql|toml|ini)|[\w.-]+)"
)
_BULLET_RE = re.compile(r"^\s*(?:[-*]|\d+[.)])\s+(.*)$")

# Signals that a task can often be advanced substantially by deterministic,
# repository-local diagnostics before a model is invoked.
_DETERMINISTIC_SIGNALS = (
    "lint",
    "format",
    "compile",
    "yaml",
    "workflow syntax",
    "failing test",
    "test failure",
    "ci failure",
    "diff check",
    "dependency",
)


@dataclass(frozen=True, slots=True)
class WorkPacket:
    issue_number: str
    title: str
    labels: tuple[str, ...]
    summary: str
    acceptance_criteria: tuple[str, ...]
    file_hints: tuple[str, ...]
    constraints: tuple[str, ...]
    routing_text: str
    execution_class: str
    estimated_prompt_tokens: int
    fingerprint: str

    def render(self) -> str:
        def block(title: str, values: Iterable[str]) -> str:
            vals = tuple(values)
            if not vals:
                return ""
            return f"\n{title}:\n" + "\n".join(f"- {v}" for v in vals)

        text = (
            f"ORCHID CONTINUUM WORK PACKET\n"
            f"Issue: #{self.issue_number}\n"
            f"Title: {self.title}\n"
            f"Labels: {', '.join(self.labels) or 'none'}\n"
            f"Execution class: {self.execution_class}\n"
            f"Fingerprint: {self.fingerprint}\n\n"
            f"Goal:\n{self.summary}"
        )
        text += block("Acceptance criteria", self.acceptance_criteria)
        text += block("Likely relevant files", self.file_hints)
        text += block("Hard constraints", self.constraints)
        text += (
            "\n\nRepository context (read only as needed):\n"
            "- AGENTS.md\n"
            "- CLAUDE.md\n"
            "- docs/AGENT-OPERATING-MEMORY.md\n"
            "- docs/SOFTWARE-FACTORY-V1.md\n"
            "\nDo not re-scan unrelated repository areas unless the task evidence requires it.\n"
        )
        return text


def _clean_lines(body: str) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for raw in body.replace("\r\n", "\n").splitlines():
        line = re.sub(r"\s+", " ", raw).strip()
        if not line or line in seen:
            continue
        seen.add(line)
        result.append(line)
    return result


def _compact_summary(lines: list[str], *, max_chars: int = 5000) -> str:
    kept: list[str] = []
    total = 0
    for line in lines:
        # Drop noisy generated markers and repeated automation receipts.
        lower = line.lower()
        if lower.startswith("[oc-auto]") or lower.startswith("generated by"):
            continue
        remaining = max_chars - total
        if remaining <= 0:
            break
        piece = line[:remaining]
        kept.append(piece)
        total += len(piece) + 1
    return "\n".join(kept) or "Use the linked issue as the acceptance contract."


def _acceptance(lines: list[str]) -> tuple[str, ...]:
    values: list[str] = []
    in_acceptance = False
    for line in lines:
        lower = line.lower().rstrip(":")
        if lower in {"acceptance criteria", "acceptance", "done when", "requirements"}:
            in_acceptance = True
            continue
        if in_acceptance and line.endswith(":") and not _BULLET_RE.match(line):
            in_acceptance = False
        match = _BULLET_RE.match(line)
        if match and (in_acceptance or any(k in match.group(1).lower() for k in ("must", "should", "verify", "test", "do not"))):
            value = match.group(1).strip()
            if value not in values:
                values.append(value)
        if len(values) >= 12:
            break
    return tuple(values)


def _constraints(lines: list[str]) -> tuple[str, ...]:
    values: list[str] = []
    for line in lines:
        lower = line.lower()
        if any(token in lower for token in ("do not ", "must not ", "never ", "without owner", "owner-gated")):
            value = _BULLET_RE.sub(r"\1", line).strip()
            if value not in values:
                values.append(value)
        if len(values) >= 10:
            break
    return tuple(values)


def _execution_class(title: str, body: str, labels: tuple[str, ...]) -> str:
    combined = f"{title}\n{body}".lower()
    label_set = {x.lower() for x in labels}
    if "oc-model-required" in label_set:
        return "model"
    if "oc-deterministic" in label_set:
        return "deterministic-first"
    if any(signal in combined for signal in _DETERMINISTIC_SIGNALS):
        return "deterministic-first"
    return "model"


def build_work_packet(
    *,
    issue_number: str,
    title: str,
    body: str,
    labels: str | Iterable[str] = (),
) -> WorkPacket:
    """Build a bounded packet without any model call."""
    if isinstance(labels, str):
        parsed_labels = tuple(sorted({x for x in re.split(r"[\s,]+", labels.strip()) if x}))
    else:
        parsed_labels = tuple(sorted({str(x).strip() for x in labels if str(x).strip()}))

    lines = _clean_lines(body)
    summary = _compact_summary(lines)
    files = tuple(dict.fromkeys(_FILE_RE.findall(body)))[:20]
    criteria = _acceptance(lines)
    constraints = _constraints(lines)
    execution_class = _execution_class(title, body, parsed_labels)
    routing_text = "\n".join((title, summary, " ".join(parsed_labels)))[:7000]
    basis = "\n".join((issue_number, title, summary, ",".join(parsed_labels)))
    fingerprint = hashlib.sha256(basis.encode("utf-8")).hexdigest()[:16]

    # Conservative char->token heuristic; telemetry reports this as an estimate.
    rendered_chars = (
        len(title)
        + len(summary)
        + sum(map(len, criteria))
        + sum(map(len, files))
        + sum(map(len, constraints))
        + 700
    )
    estimated_tokens = max(1, (rendered_chars + 3) // 4)
    return WorkPacket(
        issue_number=str(issue_number),
        title=title.strip(),
        labels=parsed_labels,
        summary=summary,
        acceptance_criteria=criteria,
        file_hints=files,
        constraints=constraints,
        routing_text=routing_text,
        execution_class=execution_class,
        estimated_prompt_tokens=estimated_tokens,
        fingerprint=fingerprint,
    )
