from .models import Classification, DocumentClass

RULES=((DocumentClass.AI_RESEARCH_SYNTHESIS,("kimi","ai-generated","generated by ai")),(DocumentClass.INTELLIGENCE_REPORT,("twin-ai","grant deadline","news monitoring")),
 (DocumentClass.TAXONOMIC_WORK,("taxonomic treatment","identification key","basionym","type citation")),(DocumentClass.PRIMARY_RESEARCH,("materials and methods","results","statistical")),
 (DocumentClass.REVIEW_SYNTHESIS,("systematic review","meta-analysis","literature review")),(DocumentClass.CONSERVATION_ASSESSMENT,("recovery plan","threat assessment","conservation needs")),
 (DocumentClass.EDUCATIONAL_MATERIAL,("learning objectives","lesson plan","curriculum")),(DocumentClass.INTERNAL_ORGANIZATIONAL,("build-","architecture","roadmap","meeting minutes")),
 (DocumentClass.DATASET_OR_SUPPLEMENT,("codebook","supplementary dataset","csv")),(DocumentClass.TECHNICAL_REPORT,("technical report","project report")),(DocumentClass.BOOK_OR_CHAPTER,("chapter ","isbn")))

def classify(title:str,text:str,*,version:str="build-084-rules-1")->Classification:
    hay=f"{title}\n{text[:12000]}".casefold()
    for cls,terms in RULES:
        hits=tuple(t for t in terms if t in hay)
        if hits: return Classification(cls,None,min(.98,.62+.09*len(hits)),"RULESET",version,hits)
    return Classification(DocumentClass.OTHER,None,.25,"RULESET",version,("no deterministic class rule matched",))
